db_data:
  image: rethinkdb:2.2.4
  volumes:
    - /data
  command: /bin/true

db:
  image: rethinkdb:2.2.4
  ports:
    - 9000:8080
  volumes_from:
    - db_data

app:
  build: api
  links:
    - db:db
  # stdin_open: true
  # tty: true
  # volumes:
    # - ./api:/usr/src/app/
  command: nodemon

frontend:
  build: frontend
  links:
    - app:app
    - db:db
  ports:
    - 80:80
  # volumes:
    # - ./frontend/src:/usr/share/nginx/html
